# Visit https://foundry-rs.github.io/starknet-foundry/appendix/snfoundry-toml.html
# and https://foundry-rs.github.io/starknet-foundry/projects/configuration.html

[sncast.mainnet]
url = "https://starknet-mainnet.g.alchemy.com/starknet/version/rpc/v0_8/jnnUmSBclU68FPzLCWcfz"
block-explorer = "Voyager"
show-explorer-links = true
